version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo

  helm_container: &helm_container
    docker:
      - image: blockcluster/circleci-kubectl-base
    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-bc-app-{{ .Branch }}-{{ .Revision }}

  save_repo: &save_repo
    save_cache:
      key: repo-bc-app-{{ .Branch }}-{{ .Revision }}
      paths:
        - .

  deploy_tag_filters: &deploy_tag_filters
    filters:
      branches:
        only:
         - master
         - staging
         - dev
         - test
      tags:
        only:
          - dev
          - development
          - test
          - staging
          - production

  build_tags: &build_tags
    filters:
      branches:
        ignore:
          - master
          - dev
          - staging
          - test
          - production


jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - *save_repo

  docker_push:
    <<: *helm_container
    steps:
      - *restore_repo
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: "Docker build"
          command: ./.circleci/docker-build.sh
      - run:
          name: "Docker push"
          command: ./.circleci/docker-push.sh

workflows:
  version: 2
  build-and-push:
    jobs:
      - checkout_code:
          <<: *deploy_tag_filters
      - docker_push:
          <<: *deploy_tag_filters
          requires:
            - checkout_code
          context: aws-creds
