---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "server.name" . }}-deploy
  namespace: {{ template "server.namespace" . }}
  labels:
    name: {{ template "server.name" . }}
    app: {{ template "server.app" . }}
    release: {{ .Release.Name }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: {{ template "server.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "server.name" . }}
        app: {{ template "server.app" . }}
        env: {{ .Values.NODE_ENV }}
    spec:
{{- include "server.nodeAffinities" . | indent 6 }}
      restartPolicy: Always
      containers:
      - name: {{ template "server.name" . }}
        image: {{ .Values.image }}:{{ template "server.image-tag" . }}
        imagePullPolicy: IfNotPresent
        workingDir: /blockcluster
        env:
        - name: WEB_ENV
          value: {{ .Values.NODE_ENV | quote }}
        - name: NODE_ENV
          value: {{ .Values.NODE_ENV | quote }}
        - name: MONGO_URL
          value: {{ template "server.monogUrl" . }}
        - name: REDIS_HOST
          value: {{ template "envs.redisHost" . }}
        - name: REDIS_PORT
          value: {{ template "envs.redisPort" . }}
        - name: NAMESPACE
          value: {{ template "server.namespace" . }}
        - name: COMMIT_HASH
          value: {{ .Values.COMMIT_HASH }}
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-creds
              key: apiKey
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_ENV
          value: {{ .Values.NODE_ENV }}
        livenessProbe:
          httpGet:
            path: /ping
            port: 3000
          timeoutSeconds: 1
          periodSeconds: 5
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /ping
            port: 3000
          timeoutSeconds: 1
          periodSeconds: 5
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "0.1Gi"
            cpu: "50m"
          limits:
            memory: "0.4Gi"
            cpu: "400m"
      imagePullSecrets:
      - name: regsecret


